import { Program } from "../../types/interfaces";

export const groupProgramList: Program[] = [
  {
    coach: "Elementary Subscription",
    tagline: "Save now with our 3 month minimum subscription.",
    description: "$50.00 initial setup plus $300.00 per month",
    price: 300,
    formattedPrice: "$300/month",
    numberOfSessions: 1,
    image: "",
  },
  {
    coach: "Middle School Subscription",
    tagline: "Save now with our 3 month minimum subscription.",
    description: "$50.00 initial setup plus $300.00 per month",
    price: 300,
    formattedPrice: "$300/month",
    numberOfSessions: 1,
    image: "",
  },
  {
    coach: "High School Subscription",
    tagline: "Save now with our 3 month minimum subscription.",
    description: "$50.00 initial setup plus $300.00 per month",
    price: 300,
    formattedPrice: "$300/month",
    numberOfSessions: 1,
    image: "",
  },
];

export const privateProgramList: Program[] = [
  {
    coach: "College",
    tagline: "Private Training",
    description: "1 on 1 Training",
    price: 425,
    formattedPrice: "$425",
    numberOfSessions: 5,
    image: "",
  },
  {
    coach: "Curtis",
    tagline: "Private Training",
    description: "1 on 1 Training",
    price: 300,
    formattedPrice: "$300",
    numberOfSessions: 5,
    image: "",
  },
  {
    coach: "Private Training",
    tagline: "",
    description: "1 on 1 Training",
    price: 425,
    formattedPrice: "$425",
    numberOfSessions: 5,
    image: "",
  },
  {
    coach: "Curtis",
    tagline: "Private Training",
    description: "1 on 1 Training",
    price: 300,
    formattedPrice: "$300",
    numberOfSessions: 5,
    image: "",
  },

  {
    coach: "College",
    tagline: "Private Training",
    description: "1 on 1 Training",
    price: 750,
    formattedPrice: "$750",
    numberOfSessions: 10,
    image: "",
  },
  {
    coach: "Curtis",
    tagline: "Private Training",
    description: "1 on 1 Training",
    price: 100,
    formattedPrice: "$100",
    numberOfSessions: 10,
    image: "",
  },
  {
    coach: "Private Training",
    tagline: "",
    description: "1 on 1 Training",
    price: 750,
    formattedPrice: "$750",
    numberOfSessions: 10,
    image: "",
  },
  {
    coach: "College",
    tagline: "Private Training",
    description: "1 on 1 Training",
    price: 1300,
    formattedPrice: "$1300",
    numberOfSessions: 20,
    image: "",
  },
  {
    coach: "Curtis",
    tagline: "Private Training",
    description: "1 on 1 Training",
    price: 800,
    formattedPrice: "$800",
    numberOfSessions: 20,
    image: "",
  },
  {
    coach: "Private Training",
    tagline: "",
    description: "1 on 1 Training",
    price: 1300,
    formattedPrice: "$1300",
    numberOfSessions: 20,
    image: "",
  },
];
