import { Program } from "../../types/interfaces";
import { programPicture1, programPicture10, programPicture11, programPicture12, programPicture2, programPicture3, programPicture4, programPicture5, programPicture6, programPicture7, programPicture8, programPicture9 } from "../../utils/pictureInfo";

export const groupProgramList: Program[] = [
  {
    coach: "Elementary Subscription",
    tagline: "Save now with our 3 month minimum subscription.",
    description: "$50.00 initial setup plus $300.00 per month",
    price: 300,
    formattedPrice: "$300/month",
    numberOfSessions: 1,
    image: programPicture8,
  },
  {
    coach: "Middle School Subscription",
    tagline: "Save now with our 3 month minimum subscription.",
    description: "$50.00 initial setup plus $300.00 per month",
    price: 300,
    formattedPrice: "$300/month",
    numberOfSessions: 1,
    image: programPicture9,
  },
  {
    coach: "High School Subscription",
    tagline: "Save now with our 3 month minimum subscription.",
    description: "$50.00 initial setup plus $300.00 per month",
    price: 300,
    formattedPrice: "$300/month",
    numberOfSessions: 1,
    image: programPicture10,
  },
];

export const privateProgramList: Program[] = [
  {
    coach: "College",
    tagline: "Private Training",
    description: "1 on 1 Training",
    price: 425,
    formattedPrice: "$425",
    numberOfSessions: 5,
    image: programPicture11,
  },
  {
    coach: "Curtis",
    tagline: "Private Training",
    description: "1 on 1 Training",
    price: 300,
    formattedPrice: "$300",
    numberOfSessions: 5,
    image: programPicture12,
  },
  {
    coach: "Private Training",
    tagline: "Private Training",
    description: "1 on 1 Training",
    price: 425,
    formattedPrice: "$425",
    numberOfSessions: 5,
    image: programPicture1 ,
  },
  {
    coach: "Curtis",
    tagline: "Private Training",
    description: "1 on 1 Training",
    price: 300,
    formattedPrice: "$300",
    numberOfSessions: 5,
    image: programPicture2,
  },

  {
    coach: "College",
    tagline: "Private Training",
    description: "1 on 1 Training",
    price: 750,
    formattedPrice: "$750",
    numberOfSessions: 10,
    image: programPicture3,
  },
  {
    coach: "Curtis",
    tagline: "Private Training",
    description: "1 on 1 Training",
    price: 100,
    formattedPrice: "$100",
    numberOfSessions: 10,
    image: programPicture4,
  },
  {
    coach: "Private Training",
    tagline: "Private Training",
    description: "1 on 1 Training",
    price: 750,
    formattedPrice: "$750",
    numberOfSessions: 10,
    image: programPicture5,
  },
  {
    coach: "College",
    tagline: "Private Training",
    description: "1 on 1 Training",
    price: 1300,
    formattedPrice: "$1300",
    numberOfSessions: 20,
    image: programPicture6,
  },
  {
    coach: "Curtis",
    tagline: "Private Training",
    description: "1 on 1 Training",
    price: 800,
    formattedPrice: "$800",
    numberOfSessions: 20,
    image: programPicture7,
  },
];
