import logo from "../assets/logo.png";
import picture1 from "../assets/person/6I2A9444.jpg";
import picture2 from "../assets/person/6I2A9446.jpg";
import picture3 from "../assets/person/6I2A9458.jpg";
import picture4 from "../assets/person/6I2A9471.jpg";
import picture5 from "../assets/person/6I2A9477.jpg";
import picture6 from "../assets/person/6I2A9478.jpg";
import picture7 from "../assets/person/6I2A9483.jpg";
import picture8 from "../assets/person/6I2A9491.jpg";
import picture9 from "../assets/person/6I2A9499.jpg";
import picture10 from "../assets/person/6I2A9504.jpg";
import picture11 from "../assets/person/6I2A9515.jpg";
import picture12 from "../assets/person/6I2A9560.jpg";

export const siteLogo = logo;
export const programPicture1 = picture1;
export const programPicture2 = picture2;
export const programPicture3 = picture3;
export const programPicture4 = picture4;
export const programPicture5 = picture5;
export const programPicture6 = picture6;
export const programPicture7 = picture7;
export const programPicture8 = picture8;
export const programPicture9 = picture9;
export const programPicture10 = picture10;
export const programPicture11 = picture11;
export const programPicture12 = picture12;